### ISSUE TITLE
application module compilation errors are silent

### ISSUE THREAD

**Issue by kubukoz** [propensive/fury-old#144] opened 2019-01-17 11:30 UTC
If an application module's sources don't compile, the error isn't reported when builing that module.

**Comment by propensive** [comment] 2019-01-17 11:57
This is a duplicate of #138. I've given it to myself to fix, as I wrote that code in a hurry right before releasing v0.3.0. ;)

**Comment by propensive** [comment] 2019-01-17 11:58
Closing this one as a duplicate, though.

**Closed as completed by propensive** 2019-01-17 11:58 UTC
Labels: bug, duplicate, good first issue, important, backend
