### ISSUE TITLE
regression on `bad-commands` test

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#1330] opened 2020-05-03 21:27 UTC
This appears to have stopped working again.

**Comment by odisseus** [comment] 2020-05-04 14:23
This is a duplicate of #1088.

**Closed as completed by odisseus** 2020-05-04 14:23 UTC
Labels: bug, duplicate, minor, user interface

**Comment by odisseus** [comment] 2020-05-04 14:28
The regression seems to be caused by this change: https://github.com/propensive/fury/pull/1282/files#diff-585434c8ce4e375972307bf1bc53ab50L201
